### ISSUE TITLE
The Noun Project

### ISSUE THREAD

**Issue by sgdwn** [WordPress/openverse-catalog#1043]
### Source Site

https://thenounproject.com/

### Value Provided

Wide variety of svg files licensed under Creative Commons and Public Domain

### Licenses Provided

CC BY, PD

### Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by obulat** [comment]
Thank you for adding this source, @sgdwn!
I am going to close this issue (and, in fact, another one like it) because they are duplicates of #45. 
It's been a long time since this source was requested. We are currently working on improving the current sources, and the search relevance, so this hasn't been worked on yet. Would you be interested in adding this integration to Openverse?
