### ISSUE TITLE
Verify Freesound data

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#346]
## Description

We received this information from Frederic Font of Freesound:

> * Note that not all files are wav, so the "Download WAV" button sometimes might not be right (not sure if you're adapting it to every sound)
> * Also the format in "Audio information" seems to be wrong (maybe not always)

Nothing immediately stands out to me from the provider script that would indicate we're gathering this info incorrectly, but we should do a more thorough investigation of the script to ensure it's accurate.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by AetherUnbound** [comment]
Some examples:
* https://search.openverse.engineering/audio/8c68ebc1-3454-487e-aebf-ecdb6047be83
* https://search.openverse.engineering/audio/fe86a4db-2df7-48e0-b198-b2b846cceb12

**Comment by AetherUnbound** [comment]
So we have an interesting conundrum here. Currently, we're reporting the _preview file_ as the "main file" (which, for our purposes, it is since that's the one we play). But all previews appear to be in MP3, regardless of what the original file type is. On results where the file type is in the file name (see above), this provides an obvious discrepancy. Would it be better to report the original file type instead, even if it's the one we're not playing? Should we afford the same considerations for file size/bit rate? What is considered "correct" in this case?

**Comment by zackkrida** [comment]
I think as long as the name matches the _download_ format, which it will, we should be okay.

It _would_ be nice to indicate somewhere to audiophiles that the contents in Openverse are a _preview_, not necessarily the full quality result. I'm not sure of the best place to do that.

**Comment by sarayourfriend** [comment]
The preview file is the correct file to set as the "main file" as that is what is used by the frontend to preview the file. With freesound in particular there's nothing else we _can_ set it ti anyway.

The `alt_files` are specifically the downloadable files, for Freesound that's only the canonical file that requires authentication to get to.

The filetype on the root audio result is basically ignored by the frontend.

The problem is that the alt_files array is the only way to indicate a _list_ of available formats for downloading. For Freesound that's only a single canonical file. For other providers there may be multiple downloadable formats. In either case, the root audio result for that file is only used for the preview, never the download (unless there are zero alt_files listed, in which case the preview is used as the download as a fall-back).

The code that is here: https://github.com/WordPress/openverse-frontend/blob/037f2efb768fdbdcff4b875e7f7c271ff50df59f/src/components/VAudioTrack/layouts/VFullLayout.vue#L122-L136

I'm not sure what any of this means for actual data integrity, it's just what the frontend is currently doing.

FWIW we also went around and around on this when the audio providers were being finalized and this is what we landed on after a lot of discussion, both [in this PR](https://github.com/WordPress/openverse-catalog/pull/95#discussion_r733965517) and in some synchronous chats with the team (those sync chats may have been before you started on the project @AetherUnbound)

**Comment by AetherUnbound** [comment]
Thanks so much for all the context Sara! I was drawn to the "Audio Information" at the center of the screen and that field says `MP3` for all of the results posted above. I see now that the download button is currently displaying the correct file type, which is great.

I'm having a hard time navigating the frontend code due to my unfamiliarity with it, do you know where the `Format` field in the "Audio Information" is being set?

**Comment by AetherUnbound** [comment]
Ah, I found it!
https://github.com/WordPress/openverse-frontend/blob/037f2efb768fdbdcff4b875e7f7c271ff50df59f/src/components/AudioDetails/VAudioDetails.vue#L42-L49

It looks like we are using the filetype field on the audio result. Should we maybe be using something similar to the `getFormats` function you linked here for greater accuracy?

**Comment by sarayourfriend** [comment]
Yes, I think you're right about that!

**Comment by AetherUnbound** [comment]
Okay! I'll close this ticket and make an issue for it on the frontend :slightly_smiling_face:
