### ISSUE TITLE
Use `execution_timeout` rather than `dagrun_timeout`

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#348]
## Description

Currently we're using `dagrun_timeout` to set a timeout for our provider workflows. According to [this documentation](https://airflow.apache.org/docs/apache-airflow/stable/_api/airflow/models/index.html), the `dagrun_timeout` allows one to:

> specify how long a DagRun should be up before timing out / failing, so that new DagRuns can be created. The timeout is only enforced for scheduled DagRuns.

It seems like that second sentence may not be true for v2.2.3, since we saw an instance where a manually triggered DAG run also (inappropriately) respected the `dagrun_timeout`. The `dagrun_timeout` is a bit confusing, and [has been discussed on the dev mailing list before](https://lists.apache.org/thread/h70wnb0jqod6wbxml5bvbtj5018sh3mj).

Additionally it looks like DAGs that hit the `dagrun_timeout` _skip_ rather than failing, which then doesn't trigger our failure alerting.

What we really want is [`execution_timeout` at the task level](https://airflow.apache.org/docs/apache-airflow/stable/concepts/tasks.html#timeouts). This would allow us to have fine-grain control of task execution _and_ set the tasks to failed rather than skipped once they're run (thus triggering failure alerting).

## Additional context

We should probably avoid using `dagrun_timeout` altogether, but this is a priority for the provider DAGs.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by mathemancer** [comment]
For context, the reasons we originally decided to go by DAG run rather than tasks (mostly relevant for provider API DAGs) are:
- it let us set a uniform 24 (or 23) hour DAG run time limit for each provider, since it's crucial that a given daily DAG run is done in a given day, and we didn't really have a reason to cut off before that, and
- It let us "smooth out" inconsistent per-task timing without always assuming the worst-case (this is the big one).  Some providers (for example) have massive amounts of data in some requests (partitioned by, e.g., days) and none in others.  

That said, if you want the fine-grained control per-task, you can always enforce both time outs.  I do think that it's pretty important that the "big" parallelized ones (WMC, Flickr) have the global 24 hour time out, since 
- assuming the worst case for each sub-DAG would severely impact maximum throughput, but 
- you also definitely want to make sure the 24-hour cutoff is respected so you don't fall further and further behind the daily schedule.

Regarding the "maximum throughput" problem w.r.t. per-task timeouts:  In order to ensure you're not cutting off data pulls prematurely, the timeout would need to be set for some maximum expected time for a given data pull.  For Flickr (for example) this is pretty variable based on which date is being pulled (since that's partitioned by date).  If you then add up those jobs to ensure that the overall job completes within 24 hours, you'll have an issue where you are making assumptions that force you to reduce the number of sequential tasks per day for Flickr below what they'd be if you _didn't_ assume the worst case.  On the other hand, if you scoot up the number of tasks so that they "realistically" take about 20-23 hours, then your time outs won't actually enforce completing the job within 24 hours (assuming they're set to handle the worst case).  But, the 24 hour cut off is the most important one to avoid the whole pipeline getting backed up.

Sorry for the novella; I hope it provides at least a little useful context.

**Comment by AetherUnbound** [comment]
Your context is _always_ useful :smile: I do understand the desire before respecting the 24 hour cutoff for the daily reingestion/parallelized execution DAGs. This came about as we were looking at DAGs scheduled to run monthly which might take more than 24 hours but don't need to be cut off at the 24 hour mark (e.g. Freesound). Right now we aren't running very many of the providers, hence the goal of [Milestone 1](https://github.com/WordPress/openverse-catalog/milestone/1). The larger, more complicated workflows are lower on my priority list for getting running because 1) we have so much data from them already and 2) we want to lift up some of the "higher authority" providers in the search results anyway. 

I think going forward, the following makes sense:
- If the DAG is daily & partitioned by date (`dated=True` I believe), we should keep the 24 hour `dagrun_timeout`
- For the non-date-partitioned DAGs, particularly those with the `@monthly` schedule interval, remove the `dagrun_timeout`
- In all cases, enforce a per-task-attempt data pull `execution_timeout` that is variable depending on the workflow

**Comment by AetherUnbound** [comment]
As part of #357, the loading for a given file occurs immediately after the data pull ends (either through completion or failure). Given that, I think it makes sense to enforce the `execution_timeout` _only_, since the `dagrun_timeout` will cause all tasks to skip and thus never upsert the data. This, coupled with #349, would give the same consistency and time limits without needing to use `dagrun_timeout`.

**Comment by jameslamb** [comment]
👋 @AetherUnbound I just wanted to say...thank you so much for the detailed write-up on this issue, for links to external resources, and to your and your colleagues for doing all this in public.

My company has been facing similar issues where we don't get alerted on tasks that are marked `skipped` based on violation of a `dagrun_timeout`, and finding this write-up improved my understanding of the underlying issue substantially!

**Comment by AetherUnbound** [comment]
@jameslamb That's incredibly kind, thank you! Sometimes I worry that I get too loquacious - I'm so glad that this info can be useful for others 😄🙌🏼
