### ISSUE TITLE
Configure Dependabot using a YAML config file

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-catalog#371]
## Description

For this repository, Dependabot is enabled but not configured. Adding a `.github/dependabot.yml` file should fix that. Using the file we can configure things like the update schedule and the labels to attach to the PRs made by Dependabot.

## Expectation

Dependabot should make regular, well-labeled PRs to the repository.

## Additional context

You can use the [config from the API repo](https://github.com/WordPress/openverse-api/blob/b760ca1c403265bafffda5b831033186b3d0c50f/.github/dependabot.yml) as a reference. Also see the [GitHub docs](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#about-the-dependabotyml-file) describing this config file.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by AetherUnbound** [comment]
Part of the reason we don't have dependabot set up on this repo is that Airflow is _very_ particular about its dependencies. So much so that the [installation instructions from PyPI](https://airflow.apache.org/docs/apache-airflow/stable/installation/installing-from-pypi.html) specifically describe using the provided constraints file for a given version. This constraints file dictates all of the dependencies that Airflow interacts with; it does _not_ pin dependencies for everything available in PyPI. I think we can look into using dependabot here, but we might need to restrict it to only the dev dependencies (or even just a subset of our dependencies) as it's likely that the versions dependabot suggests will conflict with the provided constraints file.

**Comment by obulat** [comment]
Unassigning myself from this issue because I'm not sure how to proceed. We are using Renovate for the other repositories now. Should we close this issue altogether?
