### ISSUE TITLE
Format "Airflow DAG Load Data Complete" duration

### ISSUE THREAD

**Issue by zackkrida** [WordPress/openverse-catalog#373]
## Description

The notifications are _amazing_! But currently show the [`duration`](https://github.com/WordPress/openverse-catalog/blob/5188b388759a00c42785ca79f0c96949396d4d68/openverse_catalog/dags/common/loader/reporting.py#L18) in seconds like this:

<img width="465" alt="CleanShot 2022-02-23 at 18 06 05@2x" src="https://user-images.githubusercontent.com/6351754/155424586-edca5525-81f2-47d5-a865-fa68d3a589b4.png">

We might want to:

- Round
- Convert to a human readable duration  (for example, "47 minutes", "1 hour", or alternatively something like "hh:mm:ss")

This is a _very_ minor concern 😄 

### Relevant file

https://github.com/WordPress/openverse-catalog/blob/5188b388759a00c42785ca79f0c96949396d4d68/openverse_catalog/dags/common/loader/reporting.py#L18

**Comment by AetherUnbound** [comment]
We'll want to tackle #377 before this, since `duration` will be a float after that and will make it easier to round/manipulate.

I think it may also be worth adding a comma separation[^1] to the record upsert count (e.g. `f"Count: {value:,}"`)

[^1]: https://docs.python.org/3/library/string.html#format-specification-mini-language
