### ISSUE TITLE
Load_data steps for `image` skipped during Wikimedia reingestion

### ISSUE THREAD

**Issue by stacimc** [WordPress/openverse-catalog#768]
## Description

During a run of `wikimedia_reingestion_workflow`, one of the `pull_data` steps timed out. In the logs, it is reported that **22,080** records were ingested before the task timed out. However, the `load_image_data` steps _were skipped_. This means that partial image data was not reingested for this day.

We should investigate further to understand why partial ingestion is not working in this case.

## Reproduction
In production, look at the `ingest_data_day_shift_1` TaskGroup for the 10-03-22 DagRun of the `wikimedia_reingestion_workflow`.

I have not yet done this, but you can attempt to reproduce this locally by manually raising an error in the `WikimediaCommonsDataIngester` after a large number of records are processed, and then observing the behavior. We should attempt to reproduce this in both the `wikimedia_commons_workflow` and `wikimedia_reingestion_workflow`, to see if it is solely an issue with reingestion.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by AetherUnbound** [comment]
_Note: this comment references Airflow directly several times, if you'd like access please contact a maintainer_

After some further investigation, I think I have found an explanation! **This appears to be a race condition similar to #919**. I poked around the task logs & XComs and I was really surprised to see that a run with 21k+ records (split between images & audio) would only have audio results. It turned out there were [6896 audio records processed](https://airflow.openverse.engineering/log?dag_id=wikimedia_reingestion_workflow&task_id=ingest_data_day_shift_1.load_audio_data_day_shift_1.load_from_s3_day_shift_1&execution_date=2022-09-25T00%3A00%3A00%2B00%3A00), which meant that we must be missing around 15k image records. However, I verified that the `Writing 100 lines from buffer to disk` occurred 213 times, which would lead us to believe that at least 21,300 records were written out to the two files. I suspected that we might have actually been clobbering filenames on disk prior to upload, and sure enough after [filtering down to the `image_tsv` keys for the failed run noted in the description](https://airflow.openverse.engineering/xcom/list/?_flt_3_run_id=scheduled__2022-09-25T00%3A00%3A00%2B00%3A00&_flt_3_dag_id=wikimedia_reingestion_workflow&_flt_2_task_id=generate_mixed_filename&_flt_3_key=image_tsv) the issue jumped out immediately:

![image](https://user-images.githubusercontent.com/10214785/210654311-91aa198f-d2e7-4506-af58-d202a683d418.png)

Due to the parallelism of the DAG, many of the filename generation tasks are run at the same second and end up generating the same filename. This means that the files they create are used by several data pull tasks and subsequently several load tasks for different day shifts. Fortunately, due to the way the write buffers work, data for _both days_ was written to the file; said another way, this didn't ultimately incur a loss of data. I was able to verify this by looking at the `day_shift_2` run (which shared the same filename): per the DAG it only processed 20k records, but the file was 34k lines (20k from day shift 2 plus the 15k from day shift 1!). I also double checked that timestamps for both day shifts were present in the file.

All that to say, I believe the solution here would be to **add further uniqueness into the filename for generation tasks within a reingestion workflow**. I think this could be done by appending the day shift if it's available, that should give us sufficient uniqueness per-ingestion file!

**Comment by stacimc** [comment]
Excellent investigation, thanks for looking into this!

I remember encountering and fixing the filename collisions when refactoring the reingestion workflows in #618, so I did some sleuthing. Initially, I did append the reingestion date to the tsv filename, but we ended up [moving it to the prefix](https://github.com/WordPress/openverse-catalog/pull/618#issuecomment-1255666089) to prevent a very long filename (and for the organizational benefits of grouping reingestion runs by their logical date). So now the uniqueness is only in _the s3 prefix_, example:

```
wikimedia_reingestion/year=2020/reingestion=2022-07-22/wikimedia_image_v001_20220922230222.tsv
```

But the collisions are now possible when writing to the _local file_ before copying to s3 😅

So, keeping the reingestion date in the prefix and adding the day_shift back should be the best of both ideas. [This commit](https://github.com/WordPress/openverse-catalog/pull/618/commits/026d4b2a88ee92bb497ce99602fa3318e516693a) may be helpful. The annoying thing about adding to the filename itself is that (short of additional refactoring) we have to pass that information through into the `MediaStore`s.
