### ISSUE TITLE
Incorrect duplicate values reported for Smithsonian

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-catalog#800]
## Description

Our most recent Smithsonian run produced some seemingly-incorrect reporting results:

![image](https://user-images.githubusercontent.com/10214785/195951396-0318d490-0166-4058-93f2-572cdd0875d5.png)

For maintainers, the relevant Airflow log link is here: https://airflow.openverse.engineering/log?dag_id=smithsonian_workflow&task_id=ingest_data.load_image_data.load_from_s3&execution_date=2022-10-02T00%3A00%3A00%2B00%3A00

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by stacimc** [comment]
This error only happens on runs where the `load_from_s3` step times out and is retried. Here's a breakdown of what the steps look like from on example incident of the bug:

First run of `load_from_s3`:
* 4,904,318 rows are loaded from the tsv into the loading table
* 0 rows found to be missing columns
* 1,076,253 rows found to have duplicate foreign ids
* The task times out during the upsert step

Second run of `load_from_s3`, as it retries:
* 4,904,318 rows **are loaded once again into the loading table**
* 0 rows found to be missing columns
* 4,904,318 rows (all the rows just added) are found to have duplicate foreign ids
* 3,827,819 rows are finally upserted

The issue is that on the retry, all of the ingested records are being loaded into the loading table _a second time_ and then are, naturally, all cleaned up as duplicates. This also affects the math for calculating duplicate urls. The final number of records upserted looks to actually be correct, so this is _only_ a reporting problem.

Some thoughts about ways to fix this:
* In `load_from_s3`, check if the loading table is populated already and skip this step if it's already done.
  * Is it possible for the load table to get into a state where only some of the data is loaded?
* Drop the load table on failure and restart the entire `load_data` TaskGroup
  * Not immediately sure how to do this; IMO this would be unnecessarily complicated
* Separate the `load_from_s3` step out into steps that can be retried independently: `load_from_s3`, `clean_data`, and `upsert_data`
  * Cleaning & upserting data could potentially be a single task
 
I think the last option is the cleanest option and am looking into this.

**Comment by AetherUnbound** [comment]
Thank you for these thorough notes and observations! I'm definitely in favor of splitting the steps out. One other alternative would be to truncate the table as a first step in the `load_to_s3` task, but it seems you already have a PR up that splits it out so let's go with that! 😄
